version: '3'
services:
  proxy:
    image: nginx
    container_name: 'proxy-3-months-training'
    ports:
      - 8080:80
    volumes:
      - ./webapp/public:/usr/share/nginx/html
      - ./setup/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./setup/php
    container_name: 'php-3-months-training'
    volumes:
      - ./webapp:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: 'db-3-months-training'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_database
    ports: 
      - 13306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'pma-3-months-training'
    ports:
      - 8888:80
    depends_on:
      - db
    environment:
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=password
